// Nette weergavenamen voor de formele Transfermarkt-clubnamen uit de dataset.
// Alleen namen die opgeschoond moeten worden staan hier; de rest blijft ongewijzigd.

const OVERRIDES: Record<string, string> = {
  // Bundesliga
  "1. Fußball- und Sportverein Mainz 05": "Mainz 05",
  "1. Fußball-Club Köln": "1. FC Köln",
  "1. Fußballclub Heidenheim 1846": "1. FC Heidenheim",
  "1. Fußballclub Union Berlin": "Union Berlin",
  "1. Nuremberg": "1. FC Nürnberg",
  "Bayer 04 Leverkusen Fußball": "Bayer Leverkusen",
  "Borussia Verein für Leibesübungen 1900 Mönchengladbach": "Borussia Mönchengladbach",
  "Eintracht Frankfurt Fußball AG": "Eintracht Frankfurt",
  "Fußball-Club Augsburg 1907": "FC Augsburg",
  "Fußball-Club St. Pauli von 1910": "FC St. Pauli",
  "Hamburger Sport Verein": "Hamburger SV",
  "Ingolstadt 04": "FC Ingolstadt",
  "Paderborn 07": "SC Paderborn",
  "RasenBallsport Leipzig": "RB Leipzig",
  "Sport-Club Freiburg": "SC Freiburg",
  "Sportverein Werder Bremen von 1899": "Werder Bremen",
  "Turn- und Sportgemeinschaft 1899 Hoffenheim Fußball-Spielbetriebs": "TSG Hoffenheim",
  "Verein für Bewegungsspiele Stuttgart 1893": "VfB Stuttgart",
  "Verein für Leibesübungen Wolfsburg": "VfL Wolfsburg",

  // Eredivisie
  "Ajax Amsterdam": "Ajax",
  "Alkmaar Zaanstreek": "AZ Alkmaar",
  "Cambuur Leeuwarden": "SC Cambuur",
  "De Graafschap Doetinchem": "De Graafschap",
  "Dordrecht": "FC Dordrecht",
  "Eindhovense Voetbalvereniging Philips Sport Vereniging": "PSV",
  "Emmen": "FC Emmen",
  "Excelsior Rotterdam": "Excelsior",
  "Feyenoord Rotterdam": "Feyenoord",
  "Fortuna Sittardia Combinatie": "Fortuna Sittard",
  "Groningen": "FC Groningen",
  "Heracles Almelo": "Heracles",
  "Nijmegen Eendracht Combinatie": "NEC Nijmegen",
  "Nooit Opgeven Altijd Doorzetten Aangenaam Door Vermaak En Nuttig Door Ontspanning Combinatie Breda":
    "NAC Breda",
  "Prins Hendrik Ende Desespereert Nimmer Combinatie Zwolle": "PEC Zwolle",
  "Roda JC Kerkrade": "Roda JC",
  "Sportclub Heerenveen": "SC Heerenveen",
  "Sportclub Telstar": "Telstar",
  "Twente": "FC Twente",
  "Utrecht": "FC Utrecht",
  "Vitesse Arnhem": "Vitesse",
  "Volendam": "FC Volendam",
  "Willem II Tilburg": "Willem II",

  // Premier League
  "Association Bournemouth": "Bournemouth",
  "Brighton and Hove Albion": "Brighton",
  "Leeds United Association": "Leeds United",
  "Queens Park Rangers": "QPR",
  "Sunderland Association": "Sunderland",
  "Tottenham Hotspur": "Tottenham",
  "West Bromwich Albion": "West Brom",
  "West Ham United": "West Ham",
  "Wolverhampton Wanderers": "Wolves",

  // La Liga
  "Athletic Club Bilbao": "Athletic Bilbao",
  "Club Atlético Osasuna": "Osasuna",
  "Club Atlético de Madrid S.A.D": "Atlético Madrid",
  "Deportivo Alavés S. A. D": "Deportivo Alavés",
  "Deportivo de La Coruña": "Deportivo La Coruña",
  "Elche Club de Fútbol S.A.D": "Elche",
  "Futbol Club Barcelona": "Barcelona",
  "Getafe Club de Fútbol S. A. D. Team Dubai": "Getafe",
  "Girona Fútbol Club S. A. D": "Girona",
  "Levante Unión Deportiva S.A.D": "Levante",
  "Rayo Vallecano de Madrid S. A. D": "Rayo Vallecano",
  "Real Betis Balompié S.A.D": "Real Betis",
  "Real Club Celta de Vigo S. A. D": "Celta Vigo",
  "Real Club Deportivo Mallorca S.A.D": "Mallorca",
  "Real Madrid Club de Fútbol": "Real Madrid",
  "Real Oviedo S.A.D": "Real Oviedo",
  "Real Sociedad de Fútbol S.A.D": "Real Sociedad",
  "Reial Club Deportiu Espanyol de Barcelona S.A.D": "Espanyol",
  "Sevilla Fútbol Club S.A.D": "Sevilla",
  "UD Almería": "Almería",
  "UD Las Palmas": "Las Palmas",
  "Valencia Club de Fútbol S. A. D": "Valencia",
  "Villarreal Club de Fútbol S.A.D": "Villarreal",

  // Serie A
  "Associazione Calcio Fiorentina": "Fiorentina",
  "Associazione Calcio Milan": "AC Milan",
  "Associazione Sportiva Roma": "AS Roma",
  "Atalanta Bergamasca Calcio S.p.a": "Atalanta",
  "Benevento Calcio": "Benevento",
  "Bologna 1909": "Bologna",
  "Brescia Calcio": "Brescia",
  "Cagliari Calcio": "Cagliari",
  "Calcio Como": "Como",
  "Chievo Verona": "Chievo",
  "Delfino Pescara 1936": "Pescara",
  "Frosinone Calcio": "Frosinone",
  "Genoa Cricket and": "Genoa",
  "Internazionale Milano S.p.A": "Inter Milan",
  "Livorno 1915": "Livorno",
  "Parma Calcio 1913": "Parma",
  "Pisa Sporting Club": "Pisa",
  "Salernitana 1919": "Salernitana",
  "Società Sportiva Calcio Napoli": "Napoli",
  "Società Sportiva Lazio S.p.A": "Lazio",
  "Spezia Calcio": "Spezia",
  "Torino Calcio": "Torino",
  "Udinese Calcio": "Udinese",
  "Unione Sportiva Cremonese S.p.A": "Cremonese",
  "Unione Sportiva Lecce": "Lecce",
  "Unione Sportiva Sassuolo Calcio": "Sassuolo",
  "Verona Hellas": "Hellas Verona",

  // Ligue 1
  "Ajaccio": "AC Ajaccio",
  "Angers Sporting Club de l'Ouest": "Angers",
  "Association de la Jeunesse auxerroise": "Auxerre",
  "Association sportive de Monaco": "AS Monaco",
  "Clermont Foot 63": "Clermont Foot",
  "Dijon FCO": "Dijon",
  "EA Guingamp": "Guingamp",
  "ESTAC Troyes": "Troyes",
  "Girondins Bordeaux": "Bordeaux",
  "Le Havre Athletic Club": "Le Havre",
  "Lille Olympique Sporting Club": "Lille",
  "Lorient-Bretagne Sud": "Lorient",
  "Montpellier HSC": "Montpellier",
  "Nancy-Lorraine": "Nancy",
  "Nîmes Olympique": "Nîmes",
  "Olympique Gymnaste Club Nice Côte d'Azur": "OGC Nice",
  "Olympique Lyonnais": "Lyon",
  "Olympique de Marseille": "Marseille",
  "Racing Club de Lens": "Lens",
  "Racing Club de Strasbourg Alsace": "Strasbourg",
  "SM Caen": "Caen",
  "Sochaux-Montbéliard": "Sochaux",
  "Stade Reims": "Reims",
  "Stade Rennais": "Rennes",
  "Stade brestois 29": "Brest",
  "Thonon Évian Grand Genève": "Évian",
  "de Metz": "Metz",
  "de Nantes": "Nantes",

  // Primeira Liga
  "AVS Futebol SAD": "AVS",
  "Académica Coimbra": "Académica",
  "B SAD": "Belenenses SAD",
  "CS Marítimo": "Marítimo",
  "Casa Pia Atlético Clube": "Casa Pia",
  "Club Football Estrela da Amadora": "Estrela Amadora",
  "Clube Desportivo Nacional": "Nacional",
  "Clube Desportivo Santa Clara": "Santa Clara",
  "Clube Desportivo de Tondela": "Tondela",
  "Desportivo Aves (- 2020)": "Desportivo Aves",
  "Futebol Clube de Alverca": "Alverca",
  "Futebol Clube de Arouca": "Arouca",
  "Futebol Clube de Famalicão": "Famalicão",
  "Futebol Clube do Porto": "Porto",
  "GD Chaves": "Chaves",
  "Gil Vicente Futebol Clube": "Gil Vicente",
  "Grupo Desportivo Estoril Praia": "Estoril",
  "Moreirense Futebol Clube": "Moreirense",
  "Os Belenenses": "Belenenses",
  "Rio Ave Futebol Clube": "Rio Ave",
  "Sport Lisboa e Benfica": "Benfica",
  "Sporting Clube de Braga": "SC Braga",
  "Sporting Clube de Portugal": "Sporting CP",
  "União Madeira (-2021)": "União Madeira",
  "Vitória Sport Clube": "Vitória Guimarães",
};

export function cleanClubName(raw: string): string {
  return OVERRIDES[raw] ?? raw;
}
